server {
  listen 80;
  listen [::]:80;

  server_name fincharts.jamesmatanle.com;

  root /var/www/jamesmatanle.com/html/fincharts;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location ~* \.(?:csv|css|js)$ {
    expires 1d;
    add_header Pragma public;
    add_header Cache-Control 'public';
  }
}
